version: '2.1'
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run test
          name: Run tests
workflows:
  test_my_app:
    jobs:
      - build-and-test
